# Generated by Django 5.1.6 on 2025-03-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
