# Generated by Django 5.1.6 on 2025-04-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
