# Generated by Django 5.1.6 on 2025-04-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_remove_order_created_at_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
