# Generated by Django 5.1.6 on 2025-05-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_deliverystaff_orderitem_delivery_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_staff',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='DeliveryStaff',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
