# Generated by Django 5.1.6 on 2025-07-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_deliverystaff_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_staff',
        ),
        migrations.CreateModel(
            name='Assigned_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.deliverystaff')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.order')),
            ],
        ),
    ]
