# Generated by Django 5.1.6 on 2025-07-19 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_remove_orderitem_delivery_staff_assigned_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('fruits', 'FRUITS'), ('vegetables', 'VEGETABLES'), ('meat', 'MEAT'), ('currymasala', 'CURRYMASALA')], on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.category'),
        ),
    ]
