# Generated by Django 5.1.6 on 2025-07-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('fruit', 'FRUIT'), ('vegetable', 'VEGETABLE'), ('meat', 'MEAT'), ('currymasala', 'CURRYMASALA')], on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.category'),
        ),
    ]
