# Generated by Django 5.1.6 on 2025-07-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Meat', 'Meat'), ('Currymasala', 'Currymasala')], on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.category'),
        ),
    ]
