# Generated by Django 5.1.6 on 2025-07-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
    ]
